### ISSUE TITLE
cross-compiling x11-drivers/xf86-video-fbturbo install udev rules file to wrong directory

### ISSUE THREAD

**Issue by netfab** [ksa242/gentoo-cubieboard-overlay#10]
Into xf86-video-fbturbo ebuild you do \:
> \# udev rules to get the right ownership/permission for /dev/g2d.
> insinto "${ROOT%/}lib/udev/rules.d"
> doins "${FILESDIR}"/99-sunxi-g2d.rules

If you cross-compile it, udev rules file is installed into \:
> \# qlist xf86-video-fbturbo
> /usr/armv7a-hardfloat-linux-gnueabilib/udev/rules.d/99-sunxi-g2d.rules
> /usr/lib/xorg/modules/drivers/fbturbo_drv.so

I think you should use "${D}" instead of "${ROOT}". Thanks.

**Comment by netfab** [comment]
Same thing into x11-libs/libvdpau-sunxi ebuild.

**Comment by ksa242** [comment]
Using `doins` helper with ${D} is forbidden and the build will fail.

**Comment by netfab** [comment]
In fact \:
> ${D} is automatically handled for all of these functions. 

So \:
> \-       insinto "${ROOT%/}lib/udev/rules.d"
> \+       insinto "lib/udev/rules.d"

Should work.

**Comment by netfab** [comment]
yep, I confirm it works.

**Comment by ksa242** [comment]
Thank you, pushed the changes.
